version: '2'

services:
  api:
    image: phone-lookup-api
    environment:
      PORT_2: '4040'
      REDIS_URL: 'redis:6379'
    depends_on:
      - redis
    ports:
      - "127.0.0.1:4040:4040"  

  redis:
    image: redis-swiftdiaries
    ports:
      - "6379:6379"
