version: '2'

services:
  app:
    command: restapi
    build: .
    environment:
      PORT: '4040'
      REDIS_URL: redis://redis:6379'
    depends_on:
      - redis
    ports:
      - "127.0.0.1:4040:4040"  
    command: frontend
    build: .
    environment:
      PORT: '9090'
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - redis
    ports:
      - "127.0.0.1:9090:9090"

  redis:
    image: redis
    ports:
      - "6379:6379"
